In [2]:
import numpy as np

In [3]:
# Question 1

In [4]:
quest1 = np.array(["a","b","c","d","e","f","g","h","i"])
print(type(quest1))
print(quest1)
quest11 = quest1.tolist()
print(type(quest11))

<class 'numpy.ndarray'>
['a' 'b' 'c' 'd' 'e' 'f' 'g' 'h' 'i']
<class 'list'>


In [27]:
# Question 2

In [28]:
quest2 = np.array ([[1,2,3],[4,5,6],[7,8,9]])
print(quest2)
print("The sum of the diagonal of the matrice is equal to :", quest2.trace())

[[1 2 3]
 [4 5 6]
 [7 8 9]]
The sum of the diagonal of the matrice is equal to : 15


In [29]:
# Question 3

In [5]:
quest3 = np.array([[2,4,6,8],[1,3,5,7],[9,11,13,15],[0,20,25,73]])
print(quest3)
x = int(input("x = "))
print("Values bigger than", x, "are", quest3[quest3 > x])

[[ 2  4  6  8]
 [ 1  3  5  7]
 [ 9 11 13 15]
 [ 0 20 25 73]]
x = 15
Values bigger than 15 are [20 25 73]


In [18]:
# Question 4

In [15]:
a = np.array([1,2,3,4,5,6,7,8,9])
b = np.array([9,8,7,6,5,4,3,2,1])

aa = a.tolist()
bb = b.tolist()
cc = []

for i in range(len(aa)):
    cc[i] = aa[i] + bb[i]


[1, 2, 3, 4, 5, 6, 7, 8, 9] [9, 8, 7, 6, 5, 4, 3, 2, 1]


In [26]:
# Question 5